AWSTemplateFormatVersion: 2010-09-09
Description: DataBase Sever in Private Subnet

Parameters:

  VpcSelection: 
    Description: Name of an existing VPC for the EC2 instance
    Type: AWS::EC2::VPC::Id
  
  
  AZsSelection: 
    Description: Name of an existing AZs for the EC2 instance
    Type: 'AWS::EC2::Subnet::Id'    

  KeyName: 
    Description: Name of an existing EC2 key pair for SSH access to the EC2 instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair
  
  SG: 
    Description: Name of an Security Group for the EC2 instance
    Type: AWS::EC2::SecurityGroup::Id
    ConstraintDescription: must be a valid name 
  
    
  InstaceTypeParam:
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - m3.medium
      - m3.large
      - c3.large
      - c3.xlarge
    ConstraintDescription: Must be one of them
Mappings:
  EC2RegionMapping:
    us-east-1:
      AMIs: ami-0ff8a91507f77f867
    us-west-1:
      AMIs: ami-0bdb828fd58c52235
    eu-west-1:
      AMIs: ami-047bb4163c506cd98
    ap-northeast-1:
      AMIs: ami-06cd52961ce9f0d85
    ap-southeast-1:
      AMIs: ami-08569b978cc4dfa10



#In Resources Section we are gonna defice EC2 instance that will be work as an Databases Server
Resources:  

  EC2InstaneDBS:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: 
        Ref: "AZsSelection"

      InstanceType: !Ref "InstaceTypeParam"
      ImageId: !FindInMap
        - EC2RegionMapping 
        - !Ref AWS::Region 
        - AMIs
      SecurityGroupIds:
        - !Ref SG
      KeyName: !Ref "KeyName"

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash 
          yum update -y
          yum install mysql-server -y

          
                           

      Tags:
        - Key: Name
          Value: aamirDBServer 


Outputs:
  InstanceDNS:
    Value: !GetAtt EC2InstaneDBS.PublicDnsName
